### ISSUE TITLE
Installing Ax makes cuda unavailable 

### ISSUE THREAD

**Issue by AmmaraRazzaq** [facebook/Ax#717]
Installing Ax is making CUDA unavailable hence making it impossible to use gpus. Following error occurs when I try to check if cuda is available. 
>>> import torch
>>> torch.cuda.is_available()
/nfs/users/ext_mohammed.haashir/miniconda3/envs/mltemp/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /opt/conda/conda-bld/pytorch_1614378062065/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
False

**Comment by lena-kashtelyan** [comment]
We might need @Balandat's help with this one

**Comment by Balandat** [comment]
Can you give some more details about the environment you're working in? I.e. what OS you're on, the output of `conda list` prior to installing Ax and after installing Ax.

**Comment by AmmaraRazzaq** [comment]
Hi,
Thankyou for your response.
The issue is resolved. I had Pytorch 1.8.0 installed and Ax requires >= 1.8.1 version. Hence it was uninstalling the 1.8.0 version and installing the latest version of Pytorch (10.1) which could be incompatible with the cud toolkit version of 10.1 that I am using, hence making CUDA inaccessible.
I installed Pytorch 1.8.1 and then installed Ax and it works fine now.
